apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  labels:
    channel: stable
  name: {{ template "acm-aws-cluster.fullname" . }}
spec:
  releaseImage: {{ .Values.clusterReleaseImage }}