region: ${region}
baseDomain: ${base_domain}
sshKey: |
${ssh_key}  
sshPubKey: ${ssh_pub_key}
aws_id: ${aws_id}
aws_key: ${aws_key}
docker_pull_secret: 
  ${pull_secret}
cluster_network_cidr: ${network_cidr}
service_network_cidr: ${service_cidr}
clusterReleaseImage: ${cluster_release_image}