clusterNames:
  - cluster1
  - cluster2
  - cluster3

global_base_domain: ${global_base_domain}  


cockroachdb:
  conf:
    join: 
      - cockroachdb-0.cluster-1.cockroachdb.cockroachdb.svc.clusterset.local
      - cockroachdb-1.cluster-1.cockroachdb.cockroachdb.svc.clusterset.local
      - cockroachdb-2.cluster-1.cockroachdb.cockroachdb.svc.clusterset.local
      - cockroachdb-0.cluster-2.cockroachdb.cockroachdb.svc.clusterset.local
      - cockroachdb-1.cluster-2.cockroachdb.cockroachdb.svc.clusterset.local
      - cockroachdb-2.cluster-2.cockroachdb.cockroachdb.svc.clusterset.local
      - cockroachdb-0.cluster-3.cockroachdb.cockroachdb.svc.clusterset.local
      - cockroachdb-1.cluster-3.cockroachdb.cockroachdb.svc.clusterset.local
      - cockroachdb-2.cluster-3.cockroachdb.cockroachdb.svc.clusterset.local            
  fullnameOverride: cockroachdb
  statefulset:
    replicas: 3
  podAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/component: cockroachdb
              app.kubernetes.io/instance: cockroachdb
              app.kubernetes.io/name: cockroachdb
          topologyKey: failure-domain.beta.kubernetes.io/zone

  tls:
    enabled: yes
    certs:
      provided: yes
      tlsSecret: yes
      nodeSecret: cockroachdb-tls